AWSTemplateFormatVersion: 2010-09-09
Resources:
  sumpWaterLevel:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: Sump Water Sensor
      TopicName: sump-water
      Subscription:
        - Endpoint: { "Ref" : "EmailParameter" }
          Protocol: 'email'
        - Endpoint: { "Ref" : "SMSParameter" }
          Protocol: 'SMS'
  sumpHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Sump Health check failed
      AlarmDescription: |-
        # ERROR
        No Health data for Sump
      ActionsEnabled: true
      OKActions: [ ]
      AlarmActions:
        - arn:aws:sns:us-east-1:545853618712:alerts
      InsufficientDataActions: [ ]
      MetricName: IncomingLogEvents
      Namespace: AWS/Logs
      Statistic: Average
      Dimensions:
        - Name: LogGroupName
          Value: /sump/health
      Period: 3600
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching
Parameters:
  EmailParameter:
    Type: String
    Default: no-reply@sump.com
    Description: The email address to subscribe to alerts
  SMSParameter:
    Type: String
    Default: +1
    Description: The phone number to get sms alerts